In [1]:
import pandas as pd
import os
import numpy as np

In [5]:
source = "../../../../data/dfs/"
dest   = "../../../../data/total/df_0304.csv"

In [9]:
def append(source, dest):
    arr = os.listdir(source)
    df = pd.DataFrame()
    for a in arr:
        try:        
            path = source + a
            df_aux = pd.read_csv(path)
            df = pd.concat([df, df_aux], ignore_index=True, sort=False) 
        except :
            print(a)
    return df

In [10]:
df = append(source,dest)

In [11]:
len(df)

2597

In [13]:
df.head()

,degree,l,n_it,n_s,calc_energy,exact_energy,calc_struct_fac,exact_struct_fac,std_calc_energy,std_calc_struct_fac,path
0,85,12,50,4032,-0.492833,-2.055537,1.393188,0.195754,0.012709,0.015013,data/log/t_12_85_50_4032.csv
1,30,12,30,4032,-12.264557,-20.424901,2.204034,0.195754,0.602710,0.067320,data/log/t_12_30_30_4032.csv
2,341,8,1200,2016,-15.613987,-15.613988,0.084325,0.094212,0.044905,0.010953,data/log1/t_8_341_1200_2016.csv
3,305,8,30,1008,-5.183033,-9.471856,2.119048,0.094212,0.222509,0.071420,data/log/t_8_305_30_1008.csv
4,95,20,50,504,-0.274221,-3.486230,0.673438,1.052632,0.020849,0.016393,data/log/t_20_95_50_504.csv

In [14]:
df_ord = df.sort_values(by=['degree', 'l','n_it','n_s'])

In [16]:
df_ord.to_csv(dest, index=None)

In [15]:
df_ord.head(50)

,degree,l,n_it,n_s,calc_energy,exact_energy,calc_struct_fac,exact_struct_fac,std_calc_energy,std_calc_struct_fac,path
211,0,8,30,504,-10.363652,-16.513676,2.121094,0.094212,0.466725,0.072653,data/log/t_8_0_30_504.csv
1080,0,8,30,1008,-10.857240,-16.513676,2.192460,0.094212,0.477800,0.069608,data/log/t_8_0_30_1008.csv
323,0,8,30,2016,-10.741544,-16.513676,2.032738,0.094212,0.465717,0.065875,data/log/t_8_0_30_2016.csv
311,0,8,30,4032,-11.045018,-16.513676,1.996528,0.094212,0.471569,0.064513,data/log/t_8_0_30_4032.csv
478,0,8,50,504,-11.945544,-16.513676,1.726562,0.094212,0.378653,0.044642,data/log/t_8_0_50_504.csv
1998,0,8,50,1008,-12.207645,-16.513676,1.353175,0.094212,0.373874,0.050902,data/log/t_8_0_50_1008.csv
1466,0,8,50,2016,-13.790777,-16.513676,1.150794,0.094212,0.427142,0.052306,data/log/t_8_0_50_2016.csv
1700,0,8,50,4032,-13.750466,-16.513676,1.077381,0.094212,0.420566,0.056437,data/log/t_8_0_50_4032.csv
68,0,8,1200,2016,-16.513691,-16.513676,0.087302,0.094212,0.046931,0.011107,data/log1/t_8_0_1200_2016.csv
2201,0,12,30,504,-14.445860,-23.584645,2.044271,0.195754,0.713831,0.072168,data/log/t_12_0_30_504.csv
2028,0,12,30,1008,-14.486481,-23.584645,2.264550,0.195754,0.710209,0.074125,data/log/t_12_0_30_1008.csv
650,0,12,30,2016,-14.522490,-23.584645,2.242063,0.195754,0.705095,0.063526,data/log/t_12_0_30_2016.csv
2498,0,12,30,4032,-14.514528,-23.584645,2.215278,0.195754,0.704177,0.064758,data/log/t_12_0_30_4032.csv
1560,0,12,50,504,-16.169186,-23.584645,1.924479,0.195754,0.527715,0.047933,data/log/t_12_0_50_504.csv
2113,0,12,50,1008,-16.774003,-23.584645,1.875661,0.195754,0.531662,0.044721,data/log/t_12_0_50_1008.csv
1944,0,12,50,2016,-16.802457,-23.584645,1.792328,0.195754,0.544431,0.044651,data/log/t_12_0_50_2016.csv
249,0,12,50,4032,-16.668537,-23.584645,1.874008,0.195754,0.546030,0.043901,data/log/t_12_0_50_4032.csv
507,0,14,30,504,-16.749481,-27.727284,1.776786,0.343754,0.834377,0.064738,data/log/t_14_0_30_504.csv
2009,0,14,30,1008,-16.715998,-27.727284,1.984127,0.343754,0.837146,0.061478,data/log/t_14_0_30_1008.csv
435,0,14,30,2016,-16.660640,-27.727284,2.198413,0.343754,0.838159,0.059899,data/log/t_14_0_30_2016.csv
919,0,14,30,4032,-16.650317,-27.727284,2.106009,0.343754,0.840383,0.059719,data/log/t_14_0_30_4032.csv
1576,0,14,50,504,-18.307788,-27.727284,1.901786,0.343754,0.628980,0.044707,data/log/t_14_0_50_504.csv
1767,0,14,50,1008,-18.178635,-27.727284,1.907029,0.343754,0.626226,0.044698,data/log/t_14_0_50_1008.csv
2282,0,14,50,2016,-18.471585,-27.727284,2.026077,0.343754,0.628921,0.041734,data/log/t_14_0_50_2016.csv
262,0,14,50,4032,-18.660045,-27.727284,2.007370,0.343754,0.631869,0.040162,data/log/t_14_0_50_4032.csv
98,0,20,30,504,-22.847970,-38.978698,2.023437,0.489356,1.226821,0.059233,data/log/t_20_0_30_504.csv
2129,0,20,30,1008,-23.079859,-38.978698,1.728571,0.489356,1.229425,0.053192,data/log/t_20_0_30_1008.csv
1616,0,20,30,2016,-23.393569,-38.978698,1.958333,0.489356,1.237981,0.057451,data/log/t_20_0_30_2016.csv
1422,0,20,30,4032,-23.310832,-38.978698,1.975198,0.489356,1.249217,0.055835,data/log/t_20_0_30_4032.csv
2012,0,20,50,504,-24.400869,-38.978698,2.026562,0.489356,0.890430,0.043194,data/log/t_20_0_50_504.csv
1102,0,20,50,1008,-24.560908,-38.978698,1.977778,0.489356,0.893722,0.040548,data/log/t_20_0_50_1008.csv
1197,0,20,50,2016,-24.736650,-38.978698,2.022222,0.489356,0.891866,0.037857,data/log/t_20_0_50_2016.csv
1196,0,20,50,4032,-24.783091,-38.978698,1.989881,0.489356,0.903129,0.037332,data/log/t_20_0_50_4032.csv
1876,1,8,1200,2016,-16.511156,-16.511161,0.099206,0.094212,0.045301,0.010680,data/log1/t_8_1_1200_2016.csv
2212,2,8,1200,2016,-16.380937,-16.503617,0.091270,0.094212,0.056733,0.011794,data/log1/t_8_2_1200_2016.csv
1531,3,8,1200,2016,-16.491045,-16.491045,0.073413,0.094212,0.047102,0.011126,data/log1/t_8_3_1200_2016.csv
2088,4,8,1200,2016,-15.768298,-16.473450,0.176587,0.094212,0.049229,0.010921,data/log1/t_8_4_1200_2016.csv
1079,5,8,30,504,-10.647363,-16.450837,2.000000,0.094212,0.440716,0.069974,data/log/t_8_5_30_504.csv
790,5,8,30,1008,-10.741896,-16.450837,2.132937,0.094212,0.461330,0.063613,data/log/t_8_5_30_1008.csv
945,5,8,30,2016,-10.792551,-16.450837,2.077381,0.094212,0.480418,0.067718,data/log/t_8_5_30_2016.csv
991,5,8,30,4032,-10.836583,-16.450837,2.081845,0.094212,0.467234,0.067484,data/log/t_8_5_30_4032.csv
400,5,8,50,504,-11.247395,-16.450837,1.625000,0.094212,0.358199,0.043909,data/log/t_8_5_50_504.csv
890,5,8,50,1008,-12.234816,-16.450837,1.438492,0.094212,0.393852,0.055736,data/log/t_8_5_50_1008.csv
2253,5,8,50,2016,-13.752297,-16.450837,1.105159,0.094212,0.427929,0.052504,data/log/t_8_5_50_2016.csv
1136,5,8,50,4032,-12.260022,-16.450837,1.369048,0.094212,0.387090,0.047410,data/log/t_8_5_50_4032.csv
797,5,8,1200,2016,-16.450834,-16.450837,0.086310,0.094212,0.045093,0.010690,data/log1/t_8_5_1200_2016.csv
1535,5,12,30,504,-14.280481,-23.494898,2.033854,0.195754,0.694951,0.067292,data/log/t_12_5_30_504.csv
1685,5,12,30,1008,-14.281622,-23.494898,2.427249,0.195754,0.694526,0.067814,data/log/t_12_5_30_1008.csv
2120,5,12,30,2016,-14.232320,-23.494898,2.033730,0.195754,0.697070,0.063041,data/log/t_12_5_30_2016.csv
11,5,12,30,4032,-14.466234,-23.494898,2.251984,0.195754,0.709502,0.065957,data/log/t_12_5_30_4032.csv